'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { generateSustainabilityReport } from '@/ai/flows/generate-sustainability-report';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import { Logo } from '@/components/icons';

const formSchema = z.object({
  productName: z.string().min(2, 'Product name must be at least 2 characters.'),
});

type FormValues = z.infer<typeof formSchema>;

export function ProductSearchForm() {
  const [report, setReport] = useState<string | null>(null);
  const [productName, setProductName] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      productName: '',
    },
  });

  async function onSubmit(values: FormValues) {
    setIsLoading(true);
    setReport(null);
    setProductName(values.productName);

    try {
      const result = await generateSustainabilityReport(values);
      setReport(result.report);
    } catch (error) {
      console.error('Error generating report:', error);
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Failed to generate sustainability report. Please try again.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="space-y-8">
      <Card>
        <CardHeader>
          <CardTitle>Product Search</CardTitle>
          <CardDescription>Enter a product name to get its sustainability score.</CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="productName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Product Name</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Organic Cotton T-Shirt" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" disabled={isLoading} className="w-full bg-accent text-accent-foreground hover:bg-accent/90">
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating Report...
                  </>
                ) : (
                  'Generate Report'
                )}
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>

      {isLoading && (
        <div className="flex flex-col items-center justify-center text-center space-y-4">
          <Logo className="w-12 h-12 text-primary animate-pulse" />
          <p className="text-muted-foreground">Analyzing sustainability data for {form.getValues('productName')}...</p>
        </div>
      )}

      {report && (
        <Card>
          <CardHeader>
            <CardTitle className='font-headline'>Sustainability Report for: {productName}</CardTitle>
            <CardDescription>
              This report is generated by AI and provides an overview of the product's estimated environmental impact.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none text-foreground whitespace-pre-wrap">
              {report}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
